name: "💡 简化需求提交 - Simple Request"
description: "快速提交需求，由Copilot自动生成完整需求文档供审批"
title: "[Simple Request] "
labels: ["agent:requested"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🚀 简化需求提交流程
        
        只需简单描述您的需求和用意，系统将自动：
        1. **Copilot生成完整需求文档** 并提交PR供您审批
        2. 审批通过后，生成中文需求规格说明书（Spec）
        3. 生成可执行任务清单（Plan）
        4. 按顺序执行任务，每个任务由Copilot完成
        
        **注意**: 仅仓库协作者可以提交需求。

  - type: textarea
    id: requirement
    attributes:
      label: "需求描述"
      description: "简单描述您想要实现什么功能或解决什么问题"
      placeholder: |
        例如：
        我希望在用户登录后能够看到个性化的欢迎消息，显示用户名和上次登录时间。
        
        或者：
        当前系统的搜索功能太慢，我希望优化搜索性能，让用户能在1秒内看到结果。
    validations:
      required: true

  - type: textarea
    id: purpose
    attributes:
      label: "用意/目标"
      description: "说明为什么需要这个功能，要达到什么目的"
      placeholder: |
        例如：
        - 提升用户体验，让用户感受到个性化服务
        - 增加用户粘性，提高留存率
        
        或者：
        - 解决用户投诉搜索慢的问题
        - 提升系统性能，支持更多并发用户
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: "补充信息（可选）"
      description: "任何其他有助于理解需求的信息"
      placeholder: |
        - 相关的技术栈或工具
        - 参考的类似产品或功能
        - 时间要求
        - 其他约束条件
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        
        ## 📋 接下来会发生什么？
        
        1. **需求文档生成** (约5-10分钟)
           - Copilot会分析您的需求描述
           - 自动生成一份完整的需求文档
           - 创建PR供您审批
        
        2. **审批需求文档**
           - 您可以审查、修改或直接合并需求文档PR
           - 合并后自动进入下一阶段
        
        3. **自动化执行**
           - 生成Spec（需求规格说明书）
           - 生成Plan（执行计划）
           - 逐个执行任务
        
        **可用命令**:
        - `/pause` - 暂停任务派发
        - `/resume` - 恢复任务派发
        - `/abort` - 终止整个流水线

  - type: textarea
    id: marker
    attributes:
      label: "标记"
      value: "<!-- agent-simple-request -->"
    validations:
      required: false
